### ISSUE TITLE
Functionality for ensuring School Issued IDs are unique among all users in not documented

### ISSUE THREAD

**Issue by afig** [CS305-Alpha/Gradebook#9]
Our implementation requires School Issued IDs to be unique among students, instructors, and other users. (e.g. A student may not have the same ID and an instructor.) We plan to use this to identify the role of the current user without needing to rely on `CURRENT_USER`.

This will likely be implemented with a trigger or constraint on tables, however, this is not documented in any of the plans (requirements, task list, physical schema, etc).

**Comment by jrm86** [comment]
Implemented in PR #28.  Still needs documentation.

**Comment by jrm86** [comment]
Documented in M7 updates to Logical and Physical Schema (maintained on Teams).
